import { ArrowLeft, ArrowRight, CheckCircle2, Code2, ExternalLink, Gauge, Network, Route, ShieldCheck, Wrench } from 'lucide-react'
import './index.css'
import './App.css'

const protocols = [
  { name: 'A2A', label: 'Agent to agent', icon: Network, description: 'Use when an independent agent owns skills, reasoning and task state, and another agent needs to discover and delegate work to it.', points: ['Agent Card for discovery', 'Tasks, messages and artifacts', 'Remote agent stays opaque', 'Cross-framework collaboration'], deploy: <>Wrap the Agent Framework agent in an A2A server, expose HTTP, publish <code>/.well-known/agent-card.json</code>, then deploy the web service.</>, link: 'https://github.com/microsoft/agent-framework/tree/main/python/samples/04-hosting/a2a', linkLabel: 'Microsoft A2A hosting samples' },
  { name: 'MCP', label: 'Agent to tool', icon: Wrench, description: 'Use when an agent needs a standard contract to discover and invoke tools, APIs, prompts or governed data sources.', points: ['Named tools and schemas', 'Approval before invocation', 'Connection authentication', 'Reusable Foundry Toolboxes'], deploy: <>Expose streamable HTTP on Azure Container Apps or Functions, create a Foundry RemoteTool connection, restrict <code>allowed_tools</code>, then attach it to the agent.</>, link: 'https://learn.microsoft.com/en-us/azure/foundry/agents/how-to/tools/model-context-protocol', linkLabel: 'Microsoft Foundry MCP guide' },
]

const blocks = [
  ['01', 'Set the boundary', 'Define agent ownership, discovery, identity and trust before selecting a protocol.'],
  ['02', 'Deploy MCP', 'Connect a remote server, restrict tools, require approval and inspect the tool trace.'],
  ['03', 'Deploy A2A', 'Publish the Agent Card, connect a client agent and delegate one observable task.'],
  ['04', 'Combine the paths', 'Delegate to an A2A specialist that reaches governed data through an MCP tool.'],
]

const gatewayControls = [
  ['Authenticate every path', 'Reject unauthenticated model, MCP and agent calls at the gateway. Then forward only the identity and scopes required by the approved backend. Gateway authentication does not replace tool or data authorization.', 'https://learn.microsoft.com/en-us/azure/api-management/api-management-authenticate-authorize-ai-apis'],
  ['Apply one security baseline', 'Use consistent content-safety, prompt-risk, token, rate and cost policies across approved models and agents, including workloads hosted outside Foundry. Verify policy availability by APIM tier and API type.', 'https://learn.microsoft.com/en-us/azure/api-management/llm-content-safety-policy'],
  ['Route with intent', 'Route to approved model versions and backends by workload priority, capacity and resilience needs. Keep PTU or other reserved capacity decisions separate from authorization.', 'https://learn.microsoft.com/en-us/azure/api-management/backends'],
  ['Observe the full chain', 'Correlate user, agent, A2A task, MCP tool call, model backend, policy result, latency and cost. High A2A traffic needs quotas, backpressure and trace propagation before scale testing.', 'https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-llm-logs'],
]

export default function ProtocolsPage() {
  return <div className="detail-page protocol-detail-page">
    <header className="topbar workshop-topbar"><a className="partner-logos" href="./index.html" aria-label="Return to agent governance"><img className="bi-logo" src={`${import.meta.env.BASE_URL}boehringer-ingelheim.svg`} alt="Boehringer Ingelheim" /><span className="logo-divider" /><span className="microsoft-logo"><img src={`${import.meta.env.BASE_URL}microsoft-mark.svg`} alt="" /><strong>Microsoft</strong></span></a><a className="workshop-back" href="./index.html#workstreams"><ArrowLeft size={16} /> Agenda topics</a><span className="date-pill">Day 2 · A2A and MCP</span></header>
    <main>
      <section className="detail-hero protocol-detail-hero"><div><p className="eyebrow">Day 2 · protocol interoperability</p><h1>Delegate with A2A.<br /><span>Connect tools with MCP.</span></h1><p className="lede">These protocols are complementary, not competing. Govern the remote agent as an independent actor and govern each tool or data call at its own boundary.</p><a className="button primary" href="#comparison">Compare the protocols <ArrowRight size={17} /></a></div><div className="detail-principles"><span>Combined pattern</span><strong>Orchestrator</strong><strong>A2A specialist</strong><strong>MCP data tool</strong></div></section>
      <section className="section protocol-comparison" id="comparison"><div className="detail-heading light"><div><p className="eyebrow">Choose by boundary</p><h2>Agent collaboration and tool access need different controls.</h2></div><p>A2A carries work between agents. MCP exposes capabilities to an agent. Authorization still belongs at the system that owns the action or data.</p></div><div className="protocol-card-grid">{protocols.map((item) => { const Icon = item.icon; return <article key={item.name}><div className="protocol-card-title"><Icon /><div><small>{item.label}</small><h3>{item.name}</h3></div></div><p>{item.description}</p><ul>{item.points.map(point => <li key={point}><CheckCircle2 />{point}</li>)}</ul><div className="deploy-note"><Code2 /><div><strong>Deploy it</strong><span>{item.deploy}</span></div></div><a href={item.link} target="_blank" rel="noreferrer">{item.linkLabel} <ExternalLink size={14} /></a></article>})}</div><div className="combined-flow"><ShieldCheck /><div><small>Recommended showcase</small><strong>Orchestrator agent <ArrowRight /> A2A specialist <ArrowRight /> MCP data tool</strong><p>Capture the delegated task, tool invocation, caller identity and source authorization decision as one traceable proof.</p></div></div></section>
      <section className="section gateway-governance">
        <div className="detail-heading"><div><p className="eyebrow">AI gateway</p><h2>One enforcement point across models, tools and environments.</h2></div><p>APIM is the managed runtime policy layer. It provides a consistent control point without requiring every agent implementation to recreate authentication, routing, security checks and telemetry.</p></div>
        <div className="gateway-control-grid">{gatewayControls.map(([title, detail, href], index) => <a href={href} target="_blank" rel="noreferrer" key={title}><span>{index === 0 ? <ShieldCheck /> : index === 2 ? <Route /> : index === 3 ? <Gauge /> : <CheckCircle2 />}</span><h3>{title}</h3><p>{detail}</p><strong className="card-link">Open APIM topic <ExternalLink size={14} /></strong></a>)}</div>
        <div className="connector-note"><Wrench /><div><strong>Connector bonus point</strong><p>Inventory every connector as a governed dependency: owner, authentication method, delegated scopes, source permissions, supported environments, throttling, data classification and failure behavior. A convenient connector is not an authorization boundary.</p></div></div>
      </section>
      <section className="section detail-steps"><div className="detail-heading"><div><p className="eyebrow">Day 2 blocks</p><h2>Deploy each path, then connect them.</h2></div><p>No fixed times. The day closes with a combined architecture decision and named production owners.</p></div><div className="step-grid">{blocks.map(([number, title, detail]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><div className="protocol-source-links"><a href="https://a2a-protocol.org/latest/" target="_blank" rel="noreferrer">A2A specification and SDKs <ExternalLink /></a><a href="https://github.com/microsoft/agent-framework/tree/main/python/samples/04-hosting/mcp" target="_blank" rel="noreferrer">Microsoft MCP hosting samples <ExternalLink /></a><a href="https://github.com/Azure-Samples/mcp-container-ts" target="_blank" rel="noreferrer">Azure Container Apps MCP sample <ExternalLink /></a></div></section>
    </main>
    <footer><span>DataLand · A2A and MCP</span><div className="detail-footer-links"><a href="./hosted-agents.html">Back to Day 1</a><a href="./index.html">Governance position</a></div></footer>
  </div>
}